### ISSUE TITLE
Atualizar roadmap geral

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#182]
## Descrição da Mudança *

Atualizar o roadmap geral no GhPages

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [x] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.

## Tarefas *

- [ ] Passar roadmap documentado em planilha pro formato do GhPages 
- [ ] Disponibilizar roadmap no GhPages

## Critérios de Aceitação * 

- [ ] Roadmao disponível no GHPages

**Comment by drianne** [comment]
Feito diretamente na GhPages
