### ISSUE TITLE
D09 - Criar roadmap de devops

### ISSUE THREAD

**Issue by andrewlucasgs** [fga-eps-mds/2019.2-Over26#22]
## Objetivo
Definir e documentar quais os objetivos e atividades a serem desempenhados pelo DevOps. 

## Roteiro
- [x] Planejar roteiro de execução das atividades do DevOps.
- [x] Documentar planejamento e adicioná-lo ao ghpages.

## Critérios de Aceitação
- [x] Roadmap de devops disponibilizado no gh page
- [x] O doc deve apresentar de forma clara o que será entrgue pelo DevOps
