### ISSUE TITLE
Produzir RoadMap do P.O

### ISSUE THREAD

**Issue by drianne** [fga-eps-mds/2019.2-Over26#54]
## Descrição da Mudança *

Documentar o RoadMap do P.O.

## Checklist *

- [x] Esta issue tem um nome significativo.
- [x] O nome da issue está no padrão.
- [x] Esta issue tem uma descrição de fácil entendimento.
- [x] Esta issue tem uma boa definição de critérios de aceitação.
- [ ] Esta issue tem labels associadas.
- [ ] Esta issue está associada à uma milestone.
- [ ] Esta issue tem uma pontuação estimada.
## Critérios de Aceitação * 

- [ ] Deve conter as tarefas por sprint até R2
- [ ] Atividade até R1 devem estar atualizadas
-

**Comment by drianne** [comment]
Tarefa realizada e disponível no github pages da equipe.
